version: "3"

services:
  web:
    container_name: api
    build: .
    command: python /djangoapp/manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/djangoapp
    ports:
      - "8001:8001"
    depends_on:
      - db

  db:
    container_name: postgresql
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
    ports:
      - "5433:5432"

  frontend:
    container_name: app
    build:
      context: ../frontend
      dockerfile: Dockerfile
    command: npm run host
    volumes:
      - ../frontend:/frontend
      - /frontend/node_modules
    ports:
      - "5174:5173"
    depends_on:
      - web

volumes:
  postgres_data:
